#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          mmfwaudio
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start sound_server daemon
### END INIT INFO

dlogutil -v threadtime -f /var/log/mmfw_audio.log -r 1000 -n 10 MMFW_AVAUDIO:W MMFW_SOUND MMFW_SESSIONMGR &
