#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          soundserver
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start sound_server daemon
### END INIT INFO


if [ -x /usr/bin/sound_server ]; then
        /usr/bin/sound_server -S&
fi 
